
import * as d from './proxies.generated';

export const DIRECTIVES = [
d.AcAvatar,
  d.AcBadge,
  d.AcButton,
  d.AcCard,
  d.AcCheck,
  d.AcDatePicker,
  d.AcGauge,
  d.AcHeader,
  d.AcInput,
  d.AcInputBase,
  d.AcLayout,
  d.AcLogin,
  d.AcMenu,
  d.AcMenuItem,
  d.AcModal,
  d.AcModalController,
  d.AcNavdrawer,
  d.AcOverlay,
  d.AcPagination,
  d.AcPanel,
  d.AcPanelController,
  d.AcPopper,
  d.AcPortal,
  d.AcProgress,
  d.AcSelect,
  d.AcStepper,
  d.AcTab,
  d.AcTable,
  d.AcTabs,
  d.AcToast,
  d.AcToastController,
  d.AcUpload
];
