# See documentation at https://stylelint.io/
extends:
  - stylelint-config-rational-order

indentation: 2

ignoreFiles:
  - src/global/css/layout/**/*.scss

rules:
  declaration-no-important: null
  block-closing-brace-newline-before: always
  block-opening-brace-newline-after: always
  custom-property-empty-line-before:
    - always
    - except:
        - after-comment
        - after-custom-property
        - first-nested
  rule-empty-line-before: null
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-blockless
        - first-nested
      ignore:
        - after-comment

  max-empty-lines: 2
  max-line-length: 120
  block-no-empty: true
  order/order:
    - dollar-variables
    - custom-properties
    - declarations
    - rules
  property-blacklist:
    - float
  string-quotes: double
