name: Publish Latest

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Publish
      run: |
        npm run publish-latest
