name: Publish Latest
on:
  push:
    tags:
      - '*'

jobs:
  publish-latest:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout branch master
    - uses: actions/checkout@master
    - name: Setup Node.js for use with actions
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm run publish-latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
